CREATE DATABASE IF NOT EXISTS keystone;

GRANT ALL PRIVILEGES ON keystone.* TO 'KEYSTONE_DBUSER'@'localhost' IDENTIFIED BY 'KEYSTONE_DBPASS';
GRANT ALL PRIVILEGES ON keystone.* TO 'KEYSTONE_DBUSER'@'%' IDENTIFIED BY 'KEYSTONE_DBPASS';
